### ISSUE TITLE
multi-agent particle environments

### ISSUE THREAD

**Issue by SHYang1210** [shariqiqbal2810/MAAC#7] opened 2019-05-10 06:34 UTC
when i run your multi-agent particle environments,the error:
Traceback (most recent call last):
  File "/home/cherry/multiagent-particle-envs-master/bin/interactive.py", line 26, in <module>
    env.render()
  File "/home/cherry/anaconda3/envs/shyang/lib/python3.6/site-packages/gym/core.py", line 108, in render
    raise NotImplementedError
NotImplementedError

**Comment by shariqiqbal2810** [comment] 2019-05-10 07:02
Do your package versions match the ones listed in the README?

**Comment by SHYang1210** [comment] 2019-05-10 08:16
My pytorch is 0.4.0 and python is 3.6.1. The rest of the requirements are installed through PIP. I also feel that there is a problem with the version. Is it possible that my gym is the latest version installed directly by PIP?

**Comment by shariqiqbal2810** [comment] 2019-05-10 18:06
Yeah if you run `pip install gym` it will install the most recent version by default. Try `pip install gym==0.9.4`

**Comment by SHYang1210** [comment] 2019-05-11 01:59
After I tried the lower version of what you said, I found that the particle environment could generate graphics, but there was an environment where I ran simple_crypto.py and got an error:
Traceback (most recent call last):
  File "/home/cherry/multiagent-particle-envs-master/bin/interactive.py", line 26, in <module>
    env.render()
  File "/home/cherry/anaconda3/envs/shyang/lib/python3.6/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/cherry/multiagent-particle-envs-master/bin/../multiagent/environment.py", line 249, in _render
    geom.set_color(*entity.color, alpha=0.5)
TypeError: set_color() got multiple values for argument 'alpha'

I tried to run main.py of MAAC, but I did not quite understand it. Could you please instruct me how to do it? Thank you very much!

**Comment by shariqiqbal2810** [comment] 2019-05-11 03:49
I've never tested simple_crypto.py, so I am not sure what the problem is there. It's possible that I broke something in that environment when making the modifications that I did.

What parts of main.py do you not understand? You need to pass in the name of the environment and a name for your saved model and all other parameters are optional. For example, this would run the multi_speaker_listener environment and save the model with the name "test" for 25000 episodes (with all other parameters at their defaults).

`python main.py multi_speaker_listener test --n_episodes 25000`

**Comment by SHYang1210** [comment] 2019-05-11 05:48
I used the command you gave me to appear in the console of pycharm: Episodes number-number of number form. Models folder will have a multi_speaker_listener folder.

**Comment by shariqiqbal2810** [comment] 2019-05-11 06:26
It sounds like you have it running properly!

**Comment by SHYang1210** [comment] 2019-05-11 07:22
But while I was running,I can't see the particle window

**Comment by shariqiqbal2810** [comment] 2019-05-11 17:14
Yeah it doesn't render the environment during training since that would slow things down significantly. After training, you can load the saved model (I provide a method on the model class to load from a saved file) and render the environment to see how it's doing.

**Comment by SHYang1210** [comment] 2019-05-12 06:38
Sorry, I don't quite understand how to load saved files from model classes. Are they the automatically generated ”models” folder?

**Comment by shariqiqbal2810** [comment] 2019-05-12 19:21
I am going to go ahead and close this issue, since issues are generally created for reporting bugs in the code. My advice to you would be to read the code carefully, and it should answer most of your questions.

**Closed as completed by shariqiqbal2810** 2019-05-12 19:21 UTC

**Comment by SHYang1210** [comment] 2019-05-13 01:18
Ok, I will study the code carefully. Thanks for your help.
